export const leadData = {
    "data": [
        {
            "TeleSalesLeadsID": 438359,
            "PhoneNumber": "8801640836371",
            "CustomerName": "01640836371",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "kashem371",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "16/07/2024 20:33:04"
        },
        {
            "TeleSalesLeadsID": 438452,
            "PhoneNumber": "8801703684004",
            "CustomerName": "01703684004",
            "Operator": "Shakib",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "29/06/2025 23:42:07",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "r01703684004",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "14/05/2025 16:41:06",
            "RegistrationDate": "09/05/2025 15:51:43"
        },
        {
            "TeleSalesLeadsID": 438460,
            "PhoneNumber": "8801704392879",
            "CustomerName": "01704392879",
            "Operator": "Shakib",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "29/06/2025 20:06:05",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "litonkumar",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "02/06/2025 00:03:30",
            "RegistrationDate": "18/04/2025 18:24:46"
        },
        {
            "TeleSalesLeadsID": 438534,
            "PhoneNumber": "8801710849566",
            "CustomerName": "01710849566",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "admin111",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "05/02/2024 02:15:59"
        },
        {
            "TeleSalesLeadsID": 438561,
            "PhoneNumber": "8801712765261",
            "CustomerName": "01712765261",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "khan1577",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "19/06/2024 22:31:17",
            "RegistrationDate": "19/06/2024 18:17:59"
        },
        {
            "TeleSalesLeadsID": 438624,
            "PhoneNumber": "8801717002774",
            "CustomerName": "01717002774",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "rasel446",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "28/12/2024 00:43:47",
            "RegistrationDate": "23/12/2024 22:04:16"
        },
        {
            "TeleSalesLeadsID": 438654,
            "PhoneNumber": "8801718181914",
            "CustomerName": "01718181914",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "mskamal",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "29/06/2025 20:42:53",
            "RegistrationDate": "28/10/2023 19:19:51"
        },
        {
            "TeleSalesLeadsID": 438695,
            "PhoneNumber": "8801303309370",
            "CustomerName": "01303309370",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "rakibul112233",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "31/07/2023 13:49:48"
        },
        {
            "TeleSalesLeadsID": 438754,
            "PhoneNumber": "8801308948073",
            "CustomerName": "01308948073",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "esthiak",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "06/10/2023 20:14:12"
        },
        {
            "TeleSalesLeadsID": 438804,
            "PhoneNumber": "8801314271321",
            "CustomerName": "01314271321",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "mamedisinkornar",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "14/01/2024 00:52:19"
        },
        {
            "TeleSalesLeadsID": 438823,
            "PhoneNumber": "8801315894960",
            "CustomerName": "01315894960",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "khokon333",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "13/06/2023 18:28:37"
        },
        {
            "TeleSalesLeadsID": 438860,
            "PhoneNumber": "8801318906880",
            "CustomerName": "01318906880",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "shuvo880",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "03/05/2025 03:10:18"
        },
        {
            "TeleSalesLeadsID": 438871,
            "PhoneNumber": "8801319826025",
            "CustomerName": "01319826025",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "vai445",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "17/05/2024 23:06:34",
            "RegistrationDate": "17/05/2024 00:18:47"
        },
        {
            "TeleSalesLeadsID": 438875,
            "PhoneNumber": "8801320598921",
            "CustomerName": "01320598921",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "sobuj1993",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "08/04/2025 11:02:18",
            "RegistrationDate": "08/04/2025 10:18:46"
        },
        {
            "TeleSalesLeadsID": 438914,
            "PhoneNumber": "8801326091923",
            "CustomerName": "01326091923",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "ashik5181",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "21/06/2023 10:41:43"
        },
        {
            "TeleSalesLeadsID": 438925,
            "PhoneNumber": "8801327791858",
            "CustomerName": "01327791858",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "yeasinkhan1010",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "24/09/2023 19:29:40"
        },
        {
            "TeleSalesLeadsID": 438964,
            "PhoneNumber": "8801333431732",
            "CustomerName": "01333431732",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "adburrohim",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "17/12/2024 21:08:38"
        },
        {
            "TeleSalesLeadsID": 438987,
            "PhoneNumber": "8801339309943",
            "CustomerName": "01339309943",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "israfil43",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "11/06/2025 00:40:27",
            "RegistrationDate": "19/02/2025 23:59:23"
        },
        {
            "TeleSalesLeadsID": 438988,
            "PhoneNumber": "8801339390191",
            "CustomerName": "01339390191",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 438996,
            "PhoneNumber": "8801340623719",
            "CustomerName": "01340623719",
            "Operator": "Nahid",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "29/06/2025 23:59:06",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 438997,
            "PhoneNumber": "8801341277385",
            "CustomerName": "01341277385",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439002,
            "PhoneNumber": "8801400354558",
            "CustomerName": "01400354558",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439005,
            "PhoneNumber": "8801400769403",
            "CustomerName": "01400769403",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439006,
            "PhoneNumber": "8801400870607",
            "CustomerName": "01400870607",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439007,
            "PhoneNumber": "8801400971541",
            "CustomerName": "01400971541",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "achinto1541",
            "ContactPurpose": "New",
            "FTD": "Yes",
            "ReminderDateTime": "",
            "ProcessingTime": "15/09/2023 23:52:42",
            "RegistrationDate": "14/09/2023 19:49:22"
        },
        {
            "TeleSalesLeadsID": 439009,
            "PhoneNumber": "8801401536229",
            "CustomerName": "01401536229",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439017,
            "PhoneNumber": "8801402858179",
            "CustomerName": "01402858179",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "tarikul106",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "15/12/2023 19:31:55"
        },
        {
            "TeleSalesLeadsID": 439023,
            "PhoneNumber": "8801403892626",
            "CustomerName": "01403892626",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439028,
            "PhoneNumber": "8801405154097",
            "CustomerName": "01405154097",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439033,
            "PhoneNumber": "8801405988720",
            "CustomerName": "01405988720",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
          {
            "TeleSalesLeadsID": 439034,
            "PhoneNumber": "8801406124241",
            "CustomerName": "01406124241",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439035,
            "PhoneNumber": "8801406329448",
            "CustomerName": "01406329448",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439036,
            "PhoneNumber": "8801406627705",
            "CustomerName": "01406627705",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439037,
            "PhoneNumber": "8801406786780",
            "CustomerName": "01406786780",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439038,
            "PhoneNumber": "8801406945920",
            "CustomerName": "01406945920",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439039,
            "PhoneNumber": "8801407204525",
            "CustomerName": "01407204525",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439040,
            "PhoneNumber": "8801407413190",
            "CustomerName": "01407413190",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439041,
            "PhoneNumber": "8801407544851",
            "CustomerName": "01407544851",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439042,
            "PhoneNumber": "8801407734541",
            "CustomerName": "01407734541",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439043,
            "PhoneNumber": "8801407919046",
            "CustomerName": "01407919046",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439044,
            "PhoneNumber": "8801408110877",
            "CustomerName": "01408110877",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439046,
            "PhoneNumber": "8801408521370",
            "CustomerName": "01408521370",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439047,
            "PhoneNumber": "8801408795448",
            "CustomerName": "01408795448",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439048,
            "PhoneNumber": "8801408977348",
            "CustomerName": "01408977348",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439049,
            "PhoneNumber": "8801409115630",
            "CustomerName": "01409115630",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439051,
            "PhoneNumber": "8801409439303",
            "CustomerName": "01409439303",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439052,
            "PhoneNumber": "8801409674506",
            "CustomerName": "01409674506",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439053,
            "PhoneNumber": "8801410177768",
            "CustomerName": "01410177768",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439054,
            "PhoneNumber": "8801516526892",
            "CustomerName": "01516526892",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439055,
            "PhoneNumber": "8801518344047",
            "CustomerName": "01518344047",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439056,
            "PhoneNumber": "8801519105549",
            "CustomerName": "01519105549",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439057,
            "PhoneNumber": "8801531639799",
            "CustomerName": "01531639799",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439058,
            "PhoneNumber": "8801533708286",
            "CustomerName": "01533708286",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439059,
            "PhoneNumber": "8801538151420",
            "CustomerName": "01538151420",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439060,
            "PhoneNumber": "8801540393170",
            "CustomerName": "01540393170",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439061,
            "PhoneNumber": "8801553003249",
            "CustomerName": "01553003249",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439062,
            "PhoneNumber": "8801558015285",
            "CustomerName": "01558015285",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439064,
            "PhoneNumber": "8801568361726",
            "CustomerName": "01568361726",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439065,
            "PhoneNumber": "8801568775033",
            "CustomerName": "01568775033",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439067,
            "PhoneNumber": "8801572028908",
            "CustomerName": "01572028908",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
            {
            "TeleSalesLeadsID": 439068,
            "PhoneNumber": "8801575176914",
            "CustomerName": "01575176914",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439069,
            "PhoneNumber": "8801576457568",
            "CustomerName": "01576457568",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439070,
            "PhoneNumber": "8801576711919",
            "CustomerName": "01576711919",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439071,
            "PhoneNumber": "8801577198530",
            "CustomerName": "01577198530",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439072,
            "PhoneNumber": "8801580593004",
            "CustomerName": "01580593004",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439073,
            "PhoneNumber": "8801580868769",
            "CustomerName": "01580868769",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439075,
            "PhoneNumber": "8801581554704",
            "CustomerName": "01581554704",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439076,
            "PhoneNumber": "8801581811169",
            "CustomerName": "01581811169",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439077,
            "PhoneNumber": "8801586087562",
            "CustomerName": "01586087562",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439078,
            "PhoneNumber": "8801600010197",
            "CustomerName": "01600010197",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439079,
            "PhoneNumber": "8801600132892",
            "CustomerName": "01600132892",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439080,
            "PhoneNumber": "8801600215495",
            "CustomerName": "01600215495",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439081,
            "PhoneNumber": "8801600373424",
            "CustomerName": "01600373424",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439082,
            "PhoneNumber": "8801600687372",
            "CustomerName": "01600687372",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439083,
            "PhoneNumber": "8801600872292",
            "CustomerName": "01600872292",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439084,
            "PhoneNumber": "8801601021285",
            "CustomerName": "01601021285",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439085,
            "PhoneNumber": "8801601187197",
            "CustomerName": "01601187197",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439086,
            "PhoneNumber": "8801601303934",
            "CustomerName": "01601303934",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439087,
            "PhoneNumber": "8801601440857",
            "CustomerName": "01601440857",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439088,
            "PhoneNumber": "8801601598159",
            "CustomerName": "01601598159",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439089,
            "PhoneNumber": "8801601720077",
            "CustomerName": "01601720077",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439090,
            "PhoneNumber": "8801601816633",
            "CustomerName": "01601816633",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439091,
            "PhoneNumber": "8801602012669",
            "CustomerName": "01602012669",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439093,
            "PhoneNumber": "8801602251699",
            "CustomerName": "01602251699",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439094,
            "PhoneNumber": "8801602322515",
            "CustomerName": "01602322515",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "mimi2020",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": "19/10/2023 19:05:07"
        },
        {
            "TeleSalesLeadsID": 439095,
            "PhoneNumber": "8801602455874",
            "CustomerName": "01602455874",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439097,
            "PhoneNumber": "8801602655973",
            "CustomerName": "01602655973",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439098,
            "PhoneNumber": "8801602740268",
            "CustomerName": "01602740268",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439100,
            "PhoneNumber": "8801602976078",
            "CustomerName": "01602976078",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439102,
            "PhoneNumber": "8801603379073",
            "CustomerName": "01603379073",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
          {
            "TeleSalesLeadsID": 439103,
            "PhoneNumber": "8801603524536",
            "CustomerName": "01603524536",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439104,
            "PhoneNumber": "8801603642113",
            "CustomerName": "01603642113",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439105,
            "PhoneNumber": "8801603790657",
            "CustomerName": "01603790657",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439106,
            "PhoneNumber": "8801603937631",
            "CustomerName": "01603937631",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439107,
            "PhoneNumber": "8801604139902",
            "CustomerName": "01604139902",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439108,
            "PhoneNumber": "8801604237093",
            "CustomerName": "01604237093",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439109,
            "PhoneNumber": "8801604399604",
            "CustomerName": "01604399604",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439110,
            "PhoneNumber": "8801604531009",
            "CustomerName": "01604531009",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439111,
            "PhoneNumber": "8801604696322",
            "CustomerName": "01604696322",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439112,
            "PhoneNumber": "8801604831553",
            "CustomerName": "01604831553",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439114,
            "PhoneNumber": "8801605211824",
            "CustomerName": "01605211824",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439115,
            "PhoneNumber": "8801605341839",
            "CustomerName": "01605341839",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439117,
            "PhoneNumber": "8801605695641",
            "CustomerName": "01605695641",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439118,
            "PhoneNumber": "8801605878212",
            "CustomerName": "01605878212",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439120,
            "PhoneNumber": "8801606241679",
            "CustomerName": "01606241679",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439121,
            "PhoneNumber": "8801606496852",
            "CustomerName": "01606496852",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439122,
            "PhoneNumber": "8801606660954",
            "CustomerName": "01606660954",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439123,
            "PhoneNumber": "8801606853851",
            "CustomerName": "01606853851",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439125,
            "PhoneNumber": "8801607175502",
            "CustomerName": "01607175502",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439127,
            "PhoneNumber": "8801607466654",
            "CustomerName": "01607466654",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439128,
            "PhoneNumber": "8801607668598",
            "CustomerName": "01607668598",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439129,
            "PhoneNumber": "8801607860927",
            "CustomerName": "01607860927",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439130,
            "PhoneNumber": "8801608102233",
            "CustomerName": "01608102233",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439131,
            "PhoneNumber": "8801608172318",
            "CustomerName": "01608172318",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439132,
            "PhoneNumber": "8801608290712",
            "CustomerName": "01608290712",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439133,
            "PhoneNumber": "8801608369906",
            "CustomerName": "01608369906",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439134,
            "PhoneNumber": "8801608512740",
            "CustomerName": "01608512740",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439135,
            "PhoneNumber": "8801608626902",
            "CustomerName": "01608626902",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439136,
            "PhoneNumber": "8801608780175",
            "CustomerName": "01608780175",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        },
        {
            "TeleSalesLeadsID": 439137,
            "PhoneNumber": "8801608867389",
            "CustomerName": "01608867389",
            "Operator": "",
            "Remarks": "M List",
            "CreatedDateTime": "24/06/2025 16:36:42",
            "CallDateTime": "01/01/0001 00:00:00",
            "UpdatedDateTime": "",
            "CallRemarks": "",
            "CallStatus": "New",
            "RegisteredUserName": "",
            "ContactPurpose": "New",
            "FTD": "No",
            "ReminderDateTime": "",
            "ProcessingTime": "",
            "RegistrationDate": ""
        }
    ],
    "itemsCount": 11171,
    "FilterAmount": "9,999"
}